BEGIN TRY
	BEGIN TRANSACTION 
		ALTER TABLE [dbo].[TB_SOURCE_SYSTEM_INSTRUMENT] ADD PriceFactor [int] NOT NULL DEFAULT(100)
		ALTER TABLE [dbo].[TB_SOURCE_SYSTEM_INSTRUMENT] ADD PremiumFactor [int] NULL
		ALTER TABLE [dbo].[TB_SOURCE_SYSTEM_INSTRUMENT] ADD StrikeFactor [int] NULL		
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
	IF @@TRANCOUNT != 0
	BEGIN
		PRINT 'ROLLING TB_SOURCE_SYSTEM_INSTRUMENT TRANSACTION'
		PRINT ERROR_MESSAGE()

		ROLLBACK TRANSACTION 
		
		PRINT 'TB_SOURCE_SYSTEM_INSTRUMENT TRANSACTION ROLLEDBACK'
	END
END CATCH
GO


