BEGIN TRY
	BEGIN TRANSACTION 
	
		IF EXISTS (SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'TB_STRUCTURE_LEGS' AND TYPE='U')
		BEGIN
			DROP TABLE TB_STRUCTURE_LEGS
		END

		CREATE TABLE TB_STRUCTURE_LEGS
		(
			ID INT,			
			LegInstrumentTypeCode INT,
			CreatedOn DATETIME NOT NULL DEFAULT GETDATE()
		)

		ALTER TABLE TB_STRUCTURE_LEGS  WITH CHECK ADD  CONSTRAINT FK_TB_STRUCTURE_LEGS_TB_LEG_INSTRUMENT_TYPE FOREIGN KEY(LegInstrumentTypeCode)
		REFERENCES TB_LEG_INSTRUMENT_TYPE (ID)

	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
	IF @@TRANCOUNT != 0
	BEGIN
		PRINT 'ROLLING TB_STRUCTURE_LEGS TRANSACTION'
		PRINT ERROR_MESSAGE()

		ROLLBACK TRANSACTION 
		
		PRINT 'TB_STRUCTURE_LEGS TRANSACTION ROLLEDBACK'
	END
END CATCH
GO


