IF COL_LENGTH('TB_SOURCE_SYSTEM_INSTRUMENT', 'PriceFactor') IS NULL
BEGIN
	ALTER TABLE TB_SOURCE_SYSTEM_INSTRUMENT
	ADD PriceFactor INT
END
GO

IF COL_LENGTH('TB_SOURCE_SYSTEM_INSTRUMENT', 'StrikeFactor') IS NULL
BEGIN
	ALTER TABLE TB_SOURCE_SYSTEM_INSTRUMENT
	ADD StrikeFactor INT
END
GO

IF COL_LENGTH('TB_SOURCE_SYSTEM_INSTRUMENT', 'UnderlyingFactor') IS NULL
BEGIN
	ALTER TABLE TB_SOURCE_SYSTEM_INSTRUMENT
	ADD UnderlyingFactor INT
END
GO