BEGIN TRY
	BEGIN TRANSACTION 
		UPDATE [TB_SOURCE_SYSTEM_INSTRUMENT] set PriceFactor = 1 where SourceSystemID = 3;
		UPDATE [TB_SOURCE_SYSTEM_INSTRUMENT] set PremiumFactor = 100 where SourceSystemID = 1 and SecurityType = 'OPT';
		UPDATE [TB_SOURCE_SYSTEM_INSTRUMENT] set StrikeFactor = 1 where SourceSystemID = 1 and SecurityType = 'OPT';
		UPDATE [TB_SOURCE_SYSTEM_INSTRUMENT] set PremiumFactor = 1, StrikeFactor = 1 where SourceSystemID = 3 and SecurityType = 'OPT';		
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
	IF @@TRANCOUNT != 0
	BEGIN
		PRINT 'ROLLING TB_SOURCE_SYSTEM_INSTRUMENT TRANSACTION'
		PRINT ERROR_MESSAGE()

		ROLLBACK TRANSACTION 
		
		PRINT 'TB_SOURCE_SYSTEM_INSTRUMENT TRANSACTION ROLLEDBACK'
	END
END CATCH
GO


