BEGIN TRY
	BEGIN TRANSACTION 
	
		IF EXISTS (SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'TB_STRUCTURE_DISCOUNTS' AND TYPE='U')
		BEGIN
			DROP TABLE TB_STRUCTURE_DISCOUNTS
		END

		CREATE TABLE TB_STRUCTURE_DISCOUNTS
		(
			MaturityPillarCode INT NOT NULL,
			Discount FLOAT NOT NULL DEFAULT 0,
			[Date] DATETIME,
			LegInstrumentTypeCode INT,
			CreatedOn DATETIME NOT NULL DEFAULT GETDATE()
		)

		ALTER TABLE TB_STRUCTURE_DISCOUNTS  WITH CHECK ADD  CONSTRAINT FK_TB_STRUCTURE_DISCOUNTS_TB_MATURITY_PILLAR FOREIGN KEY(MaturityPillarCode)
		REFERENCES TB_MATURITY_PILLAR (ID)

		ALTER TABLE TB_STRUCTURE_DISCOUNTS  WITH CHECK ADD  CONSTRAINT FK_TB_STRUCTURE_DISCOUNTS_TB_LEG_INSTRUMENT_TYPE FOREIGN KEY(LegInstrumentTypeCode)
		REFERENCES TB_LEG_INSTRUMENT_TYPE (ID)
		

	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
	IF @@TRANCOUNT != 0
	BEGIN
		PRINT 'ROLLING TB_STRUCTURE_DISCOUNTS TRANSACTION'
		PRINT ERROR_MESSAGE()

		ROLLBACK TRANSACTION 
		
		PRINT 'TB_STRUCTURE_DISCOUNTS TRANSACTION ROLLEDBACK'
	END
END CATCH
GO


