 IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'USP_TEMP_EH_D' AND type='P')
 BEGIN
 	 DROP PROCEDURE USP_TEMP_EH_D
 END
 GO

CREATE PROCEDURE USP_TEMP_EH_D
(  
	@Date DATE,
	@EC   INT
)  
AS  
BEGIN
	
	IF NOT EXISTS
	(
		SELECT * 
		FROM TB_EXCHANGE_HOLIDAY WITH (NOLOCK)
		WHERE [Date] = @Date
			AND ExchangeCode = @EC
	)
	BEGIN
		
		PRINT 'Não existe feriado com data '+CONVERT(VARCHAR, @Date)+' e Exchange Code '+CONVERT(VARCHAR, @EC)+'.'
		RETURN

	END;

	DELETE TB_EXCHANGE_HOLIDAY
	WHERE [Date] = @Date
	AND ExchangeCode = @EC
END

GRANT EXECUTE ON USP_TEMP_EH_D TO PUBLIC
GO