BEGIN TRY
	BEGIN TRANSACTION;   

	DELETE TB_STRUCTURE_LEGS

	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (1,1)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (2,2)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (3,3)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (4,4)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (5,5)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (6,6)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (7,6)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (7,5)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (8,6)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (8,5)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (8,9)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (9,9)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (10,9)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (10,5)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (11,11)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (12,12)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (13,13)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (14,14)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (15,15)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (16,16)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (17,6)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (17,9)
	INSERT INTO TB_STRUCTURE_LEGS (ID, LegInstrumentTypeCode) VALUES (18,18)
	
	
	COMMIT TRANSACTION;    
		
END TRY
BEGIN CATCH
	IF(@@TRANCOUNT>0)
	BEGIN
		ROLLBACK TRANSACTION
	END
		
	SELECT  
		ERROR_NUMBER() AS ErrorNumber,
		ERROR_SEVERITY() AS ErrorSeverity,
		ERROR_STATE() AS ErrorState,
		ERROR_PROCEDURE() AS ErrorProcedure,
		ERROR_LINE() AS ErrorLine,
		ERROR_MESSAGE() AS ErrorMessage;  

END CATCH 

