IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'SP_EARLY_VOLATILITY_S_GET_CALIBRATION_DATES' AND TYPE = 'P')
BEGIN
    DROP PROCEDURE SP_EARLY_VOLATILITY_S_GET_CALIBRATION_DATES
END
GO

CREATE PROCEDURE [dbo].[SP_EARLY_VOLATILITY_S_GET_CALIBRATION_DATES]
AS
BEGIN
	SELECT DISTINCT [Database] 
	FROM TB_EARLY_EXPIRY_VOLATILITY_CALIBRATION
	ORDER BY [Database] DESC
END

GRANT EXECUTE ON SP_EARLY_VOLATILITY_S_GET_CALIBRATION_DATES TO PUBLIC
GO