IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'SP_EARLY_VOLATILITY_D' AND TYPE = 'P')
BEGIN
    DROP PROCEDURE SP_EARLY_VOLATILITY_D
END
GO

CREATE PROCEDURE SP_EARLY_VOLATILITY_D
(
	@ID DATETIME
)
AS
BEGIN
	DELETE TB_EARLY_EXPIRY_VOLATILITY_CALIBRATION
	FROM TB_EARLY_EXPIRY_VOLATILITY_CALIBRATION WITH(NOLOCK)
	WHERE ID = @ID
END

GRANT EXECUTE ON SP_EARLY_VOLATILITY_D TO PUBLIC
GO