IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'SP_EARLY_VOLATILITY_S_GET' AND TYPE = 'P')
BEGIN
    DROP PROCEDURE SP_EARLY_VOLATILITY_S_GET
END
GO

CREATE PROCEDURE [dbo].[SP_EARLY_VOLATILITY_S_GET]
(
	@Database DATETIME
)
AS
BEGIN
	SELECT * 
	FROM TB_EARLY_EXPIRY_VOLATILITY_CALIBRATION
	WHERE [Database] = @Database
END

GRANT EXECUTE ON SP_EARLY_VOLATILITY_S_GET TO PUBLIC
GO


