IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'SP_EARLY_VOLATILITY_S_GET_BY_ID' AND TYPE = 'P')
BEGIN
    DROP PROCEDURE SP_EARLY_VOLATILITY_S_GET_BY_ID
END
GO

CREATE PROCEDURE [dbo].[SP_EARLY_VOLATILITY_S_GET_BY_ID]
(
	@ID INT
)
AS
BEGIN
	SELECT * 
	FROM TB_EARLY_EXPIRY_VOLATILITY_CALIBRATION
	WHERE ID = @ID
END

GRANT EXECUTE ON SP_EARLY_VOLATILITY_S_GET_BY_ID TO PUBLIC
GO


