CREATE TABLE [dbo].[TB_USER] (
    [ID]       INT          IDENTITY (1, 1) NOT NULL,
    [Name]     VARCHAR (50) NOT NULL,
    [Nickname] VARCHAR (50) NOT NULL,
    [RG]       VARCHAR (50) NOT NULL,
    [CPF]      VARCHAR (50) NOT NULL,
    [Enabled]  BIT          NOT NULL,
    CONSTRAINT [PK_TB_USER] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_TB_USER_CPF] UNIQUE NONCLUSTERED ([CPF] ASC),
    CONSTRAINT [UK_TB_USER_RG] UNIQUE NONCLUSTERED ([RG] ASC)
);

